service: msgService

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          path: send
          method: post
  receiverMessage:
    handler: handler.receiver
    events:
      - http:
          path: receiver
          method: post
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: get
