service: msgService

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  send:
    timeout: 20
    handler: src/send.send
    events:
      - http:
          path: send
          method: post
  receiverMessage:
    handler: handler.receiver
    events:
      - http:
          path: receiver
          method: post
