service: msgService

provider:
  name: aws
  runtime: nodejs4.3

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          path: send
          method: post
      - sns:
          topicName: Statham-notification
          displayName: StathamSNS
          arn: arn:aws:sns:us-west-2:451967854914:Statham-notification
  receiverMessage:
    handler: handler.receiver
    events:
      - http:
          path: receiver
          method: post
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: get
